"""create_core_tables

Revision ID: f16337bc31cb
Revises: f0b0a29bc6ec
Create Date: 2026-03-21 20:29:10.229930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f16337bc31cb'
down_revision: Union[str, Sequence[str], None] = 'f0b0a29bc6ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fairness_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.DateTime(), nullable=False),
    sa.Column('disparate_impact_ratios', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bias_detected', sa.Boolean(), nullable=True),
    sa.Column('bias_severity', sa.String(length=50), nullable=True),
    sa.Column('subgroup_performance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('flagged_for_review', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fairness_metrics_report_date', 'fairness_metrics', ['report_date'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('training_date', sa.DateTime(), nullable=False),
    sa.Column('training_datasets', sa.JSON(), nullable=False),
    sa.Column('auc_roc', sa.Float(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=False),
    sa.Column('recall', sa.Float(), nullable=False),
    sa.Column('f1_score', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.Column('deprecated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('shap_global_importance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fairness_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('s3_model_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_index('idx_model_versions_deployed_at', 'model_versions', ['deployed_at'], unique=False)
    op.create_index('idx_model_versions_version', 'model_versions', ['version'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=12), nullable=True),
    sa.Column('aadhaar_verified', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Enum('BORROWER', 'ANALYST', 'SENIOR_ANALYST', 'RISK_MANAGER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('user_category', sa.Enum('FARMER', 'DAILY_WAGE_WORKER', 'GIG_WORKER', 'MSME_OWNER', 'HOMEMAKER', 'LOW_INCOME_SALARIED', name='usercategory'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aadhaar_number'),
    sa.UniqueConstraint('aadhaar_number', name='uq_aadhaar'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email', name='uq_email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('phone_number', name='uq_phone_number')
    )
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    op.create_table('admin_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('BORROWER', 'ANALYST', 'SENIOR_ANALYST', 'RISK_MANAGER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('custom_permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_admin_users_role', 'admin_users', ['role'], unique=False)
    op.create_index('idx_admin_users_user_id', 'admin_users', ['user_id'], unique=False)
    op.create_table('loan_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'PRE_SCREENING', 'ML_SCORED', 'POLICY_CHECKED', 'HOLD', 'APPROVED', 'REJECTED', 'APPEALED', name='applicationstatus'), nullable=False),
    sa.Column('application_number', sa.String(length=50), nullable=False),
    sa.Column('requested_amount', sa.Integer(), nullable=False),
    sa.Column('requested_tenure_months', sa.Integer(), nullable=False),
    sa.Column('loan_purpose', sa.String(length=255), nullable=True),
    sa.Column('fraud_score', sa.Float(), nullable=True),
    sa.Column('fraud_check_passed', sa.Boolean(), nullable=True),
    sa.Column('fraud_check_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('probability_of_default', sa.Float(), nullable=True),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('risk_band', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', name='riskband'), nullable=True),
    sa.Column('ml_model_version', sa.String(length=50), nullable=True),
    sa.Column('ml_scores_computed_at', sa.DateTime(), nullable=True),
    sa.Column('policy_checks_passed', sa.Boolean(), nullable=True),
    sa.Column('policy_check_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_decision', sa.Enum('APPROVED', 'REJECTED', 'HOLD', 'REFERRED', name='decisiontype'), nullable=True),
    sa.Column('decision_date', sa.DateTime(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('decision_overridden', sa.Boolean(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('override_by', sa.UUID(), nullable=True),
    sa.Column('override_at', sa.DateTime(), nullable=True),
    sa.Column('alternative_data_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_nominee', sa.Boolean(), nullable=True),
    sa.Column('nominee_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_number')
    )
    op.create_index('idx_loan_applications_created_at', 'loan_applications', ['created_at'], unique=False)
    op.create_index('idx_loan_applications_fraud_score', 'loan_applications', ['fraud_score'], unique=False)
    op.create_index('idx_loan_applications_status', 'loan_applications', ['status'], unique=False)
    op.create_index('idx_loan_applications_user_id', 'loan_applications', ['user_id'], unique=False)
    op.create_table('appeals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('appeal_reason', sa.Text(), nullable=False),
    sa.Column('appeal_date', sa.DateTime(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('review_decision', sa.Enum('APPROVED', 'REJECTED', 'HOLD', 'REFERRED', name='decisiontype'), nullable=True),
    sa.Column('review_date', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', name='uq_application_appeal')
    )
    op.create_index('idx_appeals_application_id', 'appeals', ['application_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(), nullable=False),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('model_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('policy_results', sa.JSON(), nullable=True),
    sa.Column('final_decision', sa.Enum('APPROVED', 'REJECTED', 'HOLD', 'REFERRED', name='decisiontype'), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('override_flag', sa.Boolean(), nullable=True),
    sa.Column('override_justification', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('indexed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('idx_audit_logs_application_id', 'audit_logs', ['application_id'], unique=False)
    op.create_index('idx_audit_logs_event_timestamp', 'audit_logs', ['event_timestamp'], unique=False)
    op.create_index('idx_audit_logs_event_type', 'audit_logs', ['event_type'], unique=False)
    op.create_index('idx_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('category_specific_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('user_category', sa.Enum('FARMER', 'DAILY_WAGE_WORKER', 'GIG_WORKER', 'MSME_OWNER', 'HOMEMAKER', 'LOW_INCOME_SALARIED', name='usercategory'), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_specific_data_application_id', 'category_specific_data', ['application_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('decision_type', sa.Enum('APPROVED', 'REJECTED', 'HOLD', 'REFERRED', name='decisiontype'), nullable=False),
    sa.Column('decision_date', sa.DateTime(), nullable=False),
    sa.Column('decided_by_user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('approved_amount', sa.Integer(), nullable=True),
    sa.Column('approved_tenure_months', sa.Integer(), nullable=True),
    sa.Column('approved_interest_rate', sa.Float(), nullable=True),
    sa.Column('estimated_emi', sa.Integer(), nullable=True),
    sa.Column('loan_tier', sa.String(length=50), nullable=True),
    sa.Column('is_override', sa.Boolean(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], ),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_decisions_application_id', 'decisions', ['application_id'], unique=False)
    op.create_index('idx_decisions_decision_date', 'decisions', ['decision_date'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('document_type', sa.Enum('LAND_PROOF', 'SALARY_SLIP', 'BANK_STATEMENT', 'AADHAR', 'PAN', 'GST_CERTIFICATE', 'KISAN_CREDIT_CARD', 'BUSINESS_REGISTRATION', 'COLLATERAL_PROOF', 'PHOTOGRAPH', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('s3_path', sa.String(length=500), nullable=False),
    sa.Column('s3_bucket', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_application_id', 'documents', ['application_id'], unique=False)
    op.create_index('idx_documents_user_id', 'documents', ['user_id'], unique=False)
    op.create_table('nominees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('aadhaar_number', sa.String(length=12), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('employment_type', sa.String(length=100), nullable=True),
    sa.Column('monthly_income', sa.Integer(), nullable=True),
    sa.Column('collateral_type', sa.String(length=100), nullable=True),
    sa.Column('collateral_value', sa.Integer(), nullable=True),
    sa.Column('collateral_verified', sa.Boolean(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verification_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', name='uq_application_nominee')
    )
    op.create_index('idx_nominees_application_id', 'nominees', ['application_id'], unique=False)
    op.create_table('shap_explanations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('base_value', sa.Float(), nullable=False),
    sa.Column('shap_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('top_positive_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('top_negative_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plain_english_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', name='uq_application_shap')
    )
    op.create_index('idx_shap_explanations_application_id', 'shap_explanations', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_shap_explanations_application_id', table_name='shap_explanations')
    op.drop_table('shap_explanations')
    op.drop_index('idx_nominees_application_id', table_name='nominees')
    op.drop_table('nominees')
    op.drop_index('idx_documents_user_id', table_name='documents')
    op.drop_index('idx_documents_application_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('idx_decisions_decision_date', table_name='decisions')
    op.drop_index('idx_decisions_application_id', table_name='decisions')
    op.drop_table('decisions')
    op.drop_index('idx_category_specific_data_application_id', table_name='category_specific_data')
    op.drop_table('category_specific_data')
    op.drop_index('idx_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_event_type', table_name='audit_logs')
    op.drop_index('idx_audit_logs_event_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_logs_application_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_appeals_application_id', table_name='appeals')
    op.drop_table('appeals')
    op.drop_index('idx_loan_applications_user_id', table_name='loan_applications')
    op.drop_index('idx_loan_applications_status', table_name='loan_applications')
    op.drop_index('idx_loan_applications_fraud_score', table_name='loan_applications')
    op.drop_index('idx_loan_applications_created_at', table_name='loan_applications')
    op.drop_table('loan_applications')
    op.drop_index('idx_admin_users_user_id', table_name='admin_users')
    op.drop_index('idx_admin_users_role', table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_model_versions_version', table_name='model_versions')
    op.drop_index('idx_model_versions_deployed_at', table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index('idx_fairness_metrics_report_date', table_name='fairness_metrics')
    op.drop_table('fairness_metrics')
    # ### end Alembic commands ###
